### ISSUE TITLE
Can't gulp, problem in Concat.json

### ISSUE THREAD

**Issue by mikhael95** [ryanelian/ryan-compiler#1]
![screenshot 43](https://cloud.githubusercontent.com/assets/19304772/24447462/48077494-149b-11e7-942f-32f3d8b0acff.png)

**Comment by ryanelian** [comment]
Hello.

The fact that you reached "Discovered 2 concatenation targets" mean that there are no problems with `concat.json`

Can you provide more information?
- Which NodeJS version are you using?
- What OS are you using.
- Do you use Yarn or NPM to restore the packages?
- Have you tried deleting `node_modules` folder then re-restoring the packages?

**Comment by mikhael95** [comment]
Okay resolved the issue, after I deleted node_modules and tried re-restoring the packages.
